apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}

      containers:
        - name: auth-server
          image: auth-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: auth-server-config
            - configMapRef:
                name: haimp-database-config
          volumeMounts:
            - name: app-volume
              mountPath: /mnt
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
spec:
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: rest-endpoint

  type: ClusterIP
